parameters:
    upload_dir: '%kernel.project_dir%/public/uploads/attachments'
    upload_public_path: 'uploads/attachments'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $uploadDir: '%upload_dir%'
            string $uploadPublicPath: '%upload_public_path%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Enum/'
            - '../src/DTO/'
            - '../src/Kernel.php'